version: "2"
services:
  redis:
    container_name: inaturalist_redis_base
    image: redis:6.0.3
    ports:
      - 6379:6379

  es:
    container_name: inaturalist_es_base
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    command: >
      /bin/sh -c "bin/elasticsearch-plugin list | grep -q analysis-kuromoji
      || bin/elasticsearch-plugin install analysis-kuromoji;
      /usr/local/bin/docker-entrypoint.sh"

  memcached:
    container_name: inaturalist_memcached_base
    image: memcached:1.6.6
    ports:
      - 11211:11211

  pg:
    container_name: inaturalist_pg_base
    image: postgis/postgis:12-3.0
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432